### ISSUE TITLE
Some questions about the method

### ISSUE THREAD

**Issue by ZTzxj** [Yuanshi9815/Video-Infinity#16]
I would like to ask if your method has speed improvements for single GPU? Why can they be generated on different GPUs at the same time when generating different frames in parallel, is there no serial relationship between each video frame?

**Comment by Yuanshi9815** [comment]
Hello ZTzxj,

1. Unfortunately, we have not yet optimized the efficiency of single-GPU inference.
2. However, our pipeline does enable context sharing among different GPUs to ensure the coherence and consistency of the output video.
