### ISSUE TITLE
What are the hardware requirements? I only have a win10 4090. Can it run?

### ISSUE THREAD

**Issue by guahunyo** [Yuanshi9815/Video-Infinity#4]

**Comment by Yuanshi9815** [comment]
The 4090 is supported, and you can run it in single GPU mode. However, we haven't conducted detailed research on Windows 10 yet, and there might be some compatibility issues with certain tools (`ffmpeg`) on Windows 10. We recommend running it on a multi GPUs setup to generate longer videos in a shorter amount of time.
