### ISSUE TITLE
pls make a gradio demo

### ISSUE THREAD

**Issue by yuvraj108c** [Yuanshi9815/Video-Infinity#6]
Awesome work, please make a gradio app for easier inferencing!

Thanks.

**Comment by Yuanshi9815** [comment]
Thank you for your interest! For single GPU inference, you can refer to this unofficial Gradio [script](https://archive.creativaier.com/video_infinity/app.zip) (thanks to [creativaier](https://www.youtube.com/watch?v=HlLK03Zxyv8) from Japan 🇯🇵). This should help facilitate easier inferencing with our model.
